/**
 * DO NOT EDIT — GENERATED FILE
 *
 * This file is generated by `scripts/gen-mobile-tailwind.ts` from
 * `src/config/design.ts`. Run `npm run gen:mobile-tw` to regenerate after
 * design tokens change. CI runs `npm run gen:mobile-tw:check` which fails
 * if this file is out of sync.
 *
 * Hand edits will be overwritten.
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  "content": [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
    "./lib/**/*.{js,jsx,ts,tsx}"
  ],
  "presets": [
    require("nativewind/preset")
  ],
  "theme": {
    "extend": {
      "colors": {
        "background": "oklch(1 0 0)",
        "foreground": "oklch(0.145 0 0)",
        "card": "oklch(1 0 0)",
        "cardForeground": "oklch(0.145 0 0)",
        "popover": "oklch(1 0 0)",
        "popoverForeground": "oklch(0.145 0 0)",
        "primary": "oklch(0.205 0 0)",
        "primaryForeground": "oklch(0.985 0 0)",
        "secondary": "oklch(0.97 0 0)",
        "secondaryForeground": "oklch(0.205 0 0)",
        "muted": "oklch(0.97 0 0)",
        "mutedForeground": "oklch(0.48 0 0)",
        "accent": "oklch(0.97 0 0)",
        "accentForeground": "oklch(0.205 0 0)",
        "destructive": "oklch(0.577 0.245 27.325)",
        "border": "oklch(0.64 0 0)",
        "input": "oklch(0.64 0 0)",
        "ring": "oklch(0.62 0 0)",
        "success": "oklch(0.48 0.16 145)",
        "successForeground": "oklch(0.985 0 0)",
        "warning": "oklch(0.78 0.16 80)",
        "warningForeground": "oklch(0.205 0 0)",
        "backgroundDark": "oklch(0.145 0 0)",
        "foregroundDark": "oklch(0.985 0 0)",
        "cardDark": "oklch(0.205 0 0)",
        "cardForegroundDark": "oklch(0.985 0 0)",
        "popoverDark": "oklch(0.205 0 0)",
        "popoverForegroundDark": "oklch(0.985 0 0)",
        "primaryDark": "oklch(0.922 0 0)",
        "primaryForegroundDark": "oklch(0.205 0 0)",
        "secondaryDark": "oklch(0.269 0 0)",
        "secondaryForegroundDark": "oklch(0.985 0 0)",
        "mutedDark": "oklch(0.269 0 0)",
        "mutedForegroundDark": "oklch(0.708 0 0)",
        "accentDark": "oklch(0.269 0 0)",
        "accentForegroundDark": "oklch(0.985 0 0)",
        "destructiveDark": "oklch(0.704 0.191 22.216)",
        "borderDark": "oklch(1 0 0 / 35%)",
        "inputDark": "oklch(1 0 0 / 40%)",
        "ringDark": "oklch(0.556 0 0)",
        "successDark": "oklch(0.7 0.18 145)",
        "successForegroundDark": "oklch(0.145 0 0)",
        "warningDark": "oklch(0.82 0.16 80)",
        "warningForegroundDark": "oklch(0.145 0 0)"
      },
      "fontSize": {
        "xs": [
          "0.75rem",
          {
            "lineHeight": "1rem"
          }
        ],
        "sm": [
          "0.875rem",
          {
            "lineHeight": "1.25rem"
          }
        ],
        "base": [
          "1rem",
          {
            "lineHeight": "1.5rem"
          }
        ],
        "lg": [
          "1.125rem",
          {
            "lineHeight": "1.75rem"
          }
        ],
        "xl": [
          "1.25rem",
          {
            "lineHeight": "1.75rem"
          }
        ],
        "2xl": [
          "1.5rem",
          {
            "lineHeight": "2rem"
          }
        ],
        "3xl": [
          "1.875rem",
          {
            "lineHeight": "2.25rem"
          }
        ],
        "4xl": [
          "2.25rem",
          {
            "lineHeight": "2.5rem"
          }
        ]
      },
      "borderRadius": {
        "base": "0.625rem",
        "sm": "calc(0.625rem * 0.6)",
        "md": "calc(0.625rem * 0.8)",
        "lg": "0.625rem",
        "xl": "calc(0.625rem * 1.4)",
        "2xl": "calc(0.625rem * 1.8)",
        "full": "9999px"
      },
      "fontFamily": {
        "sans": [
          "Geist",
          "System"
        ],
        "display": [
          "Geist",
          "System"
        ],
        "mono": [
          "GeistMono",
          "Menlo"
        ]
      }
    }
  },
  "plugins": []
};
